services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - ./client:/user/src/app
    ports:
      - "3000:3000"
    command: yarn dev
